# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# docs https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions

name: Workflow

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check code formatting
      run: |
        black --check .

    - name: Flake8 Lint
      uses: py-actions/flake8@v2

    - name: Run tests
      run: |
        if [ -d tests ]; then python -m unittest discover -s tests -v; fi
